# Generated by Django 3.2.9 on 2021-12-14 17:25

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction_of_work', models.CharField(max_length=100, verbose_name='Направление работы')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание направления')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='actual.directionslist')),
            ],
            options={
                'verbose_name': 'Направление работы',
                'verbose_name_plural': 'Направления работы',
                'ordering': ['direction_of_work'],
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(max_length=100, verbose_name='Заголовок информации')),
                ('note_text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата размещения')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('direction_of_work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actual.directionslist', verbose_name='Направление работы')),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Информации',
                'ordering': ['-updated_at'],
            },
        ),
    ]
